Update logs & handle image not exists yet

diff --git a/deploy-argocd/action.yml b/deploy-argocd/action.yml
--- a/deploy-argocd/action.yml
+++ b/deploy-argocd/action.yml
@@ -109,21 +109,29 @@ runs:
         # As a a workaround, we just pull the images and check the digests with docker inspect.
         # Another option would be docker manifest inspect which supports not pulling, but the command is experimental.
 
-        docker pull "$OLD_IMAGE"
+        if ! docker pull "$OLD_IMAGE"; then
+          echo 'Failed to pull old image. This may be expected if the image does not exist yet.'
+          echo 'Proceeding with deployment.'
+          echo 'skip-deployment=false' >> "$GITHUB_OUTPUT"
+          exit 0
+        fi
+
         docker pull "$NEW_IMAGE"
 
         old_image_digest=$(docker inspect -f '{{index .RepoDigests 0}}' "$OLD_IMAGE" | cut -d '@' -f2)
         new_image_digest=$(docker inspect -f '{{index .RepoDigests 0}}' "$NEW_IMAGE" | cut -d '@' -f2)
 
         if [[ "$old_image_digest" == "$new_image_digest" ]]; then
-          echo "Image digest has not changed from currently deployed image. Skipping deployment."
+          echo 'Image digest has not changed from currently deployed image.'
+          printf 'Skipping deployment.\n\n'
           echo "Currently deployed image: $OLD_IMAGE"
           echo "Currently deployed digest: $old_image_digest"
           echo "skip-deployment=true" >> "$GITHUB_OUTPUT"
         else
-          echo "Image digest has changed. Proceeding with deployment."
+          echo 'Image digest has changed from currently deployed image.'
+          printf 'Proceeding with deployment.\n\n'
           echo "Currently deployed image: $OLD_IMAGE"
-          echo "Currently deployed digest: $old_image_digest"
+          printf 'Currently deployed digest: %s\n\n' "$old_image_digest"
           echo "New image: $NEW_IMAGE"
           echo "New digest: $new_image_digest"
           echo "skip-deployment=false" >> "$GITHUB_OUTPUT"
