Unittests: Add check to validate test project pattern.

diff --git a/unittest/action.yml b/unittest/action.yml
--- a/unittest/action.yml
+++ b/unittest/action.yml
@@ -28,7 +28,13 @@ runs:
     - name: Run unit tests
       shell: bash
       run: |
-        testprojects=$(find . -iname '${{ inputs.test-projects }}')
+        testprojects=$(find . -iname '${{ inputs.test-projects }}')        
+        if [[ -z $testprojects ]]; then
+            echo "Unable to find any dotnet projects matching the pattern ${{ inputs.test-projects }}. Set the pattern using the parameter test-projects."
+            exit 1
+        else
+            echo "Running dotnet test on test projects: $testprojects"
+        fi
         for testproject in $testprojects;
         do
           if [[ '${{ inputs.test-coverage }}' == 'true' ]]; then
